server:
  port: 8080
  error:
    include-message: always
  ssl:
    enabled: false
    enabled-protocols: TLSv1.2
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
  tomcat:
    accesslog:
      request-attributes-enabled: true
spring:
  datasource:
    username: koyeb-adm
    password: OyQM1qId7BEe
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: jdbc:postgresql://ep-damp-shadow-a14jhbtw.ap-southeast-1.pg.koyeb.app/koyebdb
    url: jdbc:postgresql://ep-damp-shadow-a14jhbtw.ap-southeast-1.pg.koyeb.app/koyebdb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days